# Generated by Django 3.0.2 on 2020-01-11 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memez', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='thumb',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
